version: '3.5'

services:
  postgres:
    image: postgres
    container_name: dipl_server_db
    environment:
      POSTGRES_DB: diplServerDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dipl_server_db:5432/diplServerDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres